# Introducing NumPy


In [1]:
import numpy as np


# Scalars


In [2]:
s = np.array(5)


In [3]:
s


array(5)

In [4]:
s.shape


()

In [5]:
x = s + 3


In [6]:
x

8

In [7]:
x.__class__


numpy.int64

# Vector

In [8]:
v = np.array([1,2,3])


In [9]:
v

array([1, 2, 3])

In [10]:
v.shape

(3,)

In [11]:
x = v[1]
x

2

In [12]:
v[1:]

array([2, 3])

# Matrices


In [13]:
m = np.array([[1,2,3], [4,5,6], [7,8,9]])


In [14]:
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
m.shape

(3, 3)

In [16]:
 m[1][2]

6

# Tensors


In [17]:
t = np.array([[[[1],[2]],[[3],[4]],[[5],[6]]],[[[7],[8]],\
    [[9],[10]],[[11],[12]]],[[[13],[14]],[[15],[16]],[[17],[17]]]])

In [18]:
t

array([[[[ 1],
         [ 2]],

        [[ 3],
         [ 4]],

        [[ 5],
         [ 6]]],


       [[[ 7],
         [ 8]],

        [[ 9],
         [10]],

        [[11],
         [12]]],


       [[[13],
         [14]],

        [[15],
         [16]],

        [[17],
         [17]]]])

In [19]:
 t.shape

(3, 3, 2, 1)

In [20]:
 t[2][1][1][0]

16

# Changing Shapes


In [21]:
v = np.array([1,2,3,4])
v

array([1, 2, 3, 4])

In [22]:
x = v.reshape(1,4)
x

array([[1, 2, 3, 4]])

In [23]:
x


array([[1, 2, 3, 4]])

In [24]:
x = v[None, :]
x

array([[1, 2, 3, 4]])

# Element-wise Operations

In [25]:
values = [1,2,3,4,5]
for i in range(len(values)):
    values[i] += 5


In [26]:
# numpy element wise operations
values = [1,2,3,4,5]
values = np.array(values) + 5
values

array([ 6,  7,  8,  9, 10])

In [27]:
some_array = values

In [28]:
x = np.multiply(some_array, 5)
x = some_array * 5

In [29]:
x


array([30, 35, 40, 45, 50])

# Element-wise Matrix Operations


In [30]:
a = np.array([[1,3],[5,7]])
a

array([[1, 3],
       [5, 7]])

In [31]:
b = np.array([[2,4],[6,8]])
b

array([[2, 4],
       [6, 8]])

In [32]:
c = a + b
c

array([[ 3,  7],
       [11, 15]])

# Element-wise Multiplication


In [33]:
m = np.array([[1,2,3],[4,5,6]])
m

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:

n = m * 0.25
n

array([[ 0.25,  0.5 ,  0.75],
       [ 1.  ,  1.25,  1.5 ]])

In [35]:
m * n


array([[ 0.25,  1.  ,  2.25],
       [ 4.  ,  6.25,  9.  ]])

In [36]:
np.multiply(m, n)   # equivalent to m * n


array([[ 0.25,  1.  ,  2.25],
       [ 4.  ,  6.25,  9.  ]])

# Matrix Product


In [37]:
a = np.array([[1,2,3,4],[5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [38]:
a.shape


(2, 4)

In [39]:
b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [40]:
b.shape


(4, 3)

In [41]:
c = np.matmul(a, b)
c

array([[ 70,  80,  90],
       [158, 184, 210]])

In [42]:
np.matmul(b, a)


ValueError: shapes (4,3) and (2,4) not aligned: 3 (dim 1) != 2 (dim 0)

# NumPy's dot function


In [ ]:
a = np.array([[1,2],[3,4]])
a

In [ ]:
np.dot(a,a)
    

In [44]:
b.shape[1]



3

In [47]:
a


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [48]:
for row in a:
    print(row)

[1 2 3 4]
[5 6 7 8]


In [ ]:
print("Mean == {}".format(find_mean([1,3,4])))